version: 2

updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 50
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
